//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinorShift.Emuera.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MinorShift.Emuera.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {0}関数:画像の範囲外が指定されています 的本地化字符串。
        /// </summary>
        public static string RuntimeErrMesMethodCIMGCreateOutOfRange0 {
            get {
                return ResourceManager.GetString("RuntimeErrMesMethodCIMGCreateOutOfRange0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}関数:ColorARGB引数に不適切な値(0x{1:X8})が指定されました 的本地化字符串。
        /// </summary>
        public static string RuntimeErrMesMethodColorARGB0 {
            get {
                return ResourceManager.GetString("RuntimeErrMesMethodColorARGB0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}関数:第{2}引数に不適切な値({1})が指定されました 的本地化字符串。
        /// </summary>
        public static string RuntimeErrMesMethodDefaultArgumentOutOfRange0 {
            get {
                return ResourceManager.GetString("RuntimeErrMesMethodDefaultArgumentOutOfRange0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}関数:ColorMatrixの指定された要素({1}, {2})が不適切であるか5x5に足りていません 的本地化字符串。
        /// </summary>
        public static string RuntimeErrMesMethodGColorMatrix0 {
            get {
                return ResourceManager.GetString("RuntimeErrMesMethodGColorMatrix0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}関数:描画オプションがWINAPIの時には使用できません 的本地化字符串。
        /// </summary>
        public static string RuntimeErrMesMethodGDIPLUSOnly {
            get {
                return ResourceManager.GetString("RuntimeErrMesMethodGDIPLUSOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}関数:GraphicsのHeightに0以下の値({1})が指定されました 的本地化字符串。
        /// </summary>
        public static string RuntimeErrMesMethodGHeight0 {
            get {
                return ResourceManager.GetString("RuntimeErrMesMethodGHeight0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}関数:GraphicsのHeightに{2}以上の値({1})が指定されました 的本地化字符串。
        /// </summary>
        public static string RuntimeErrMesMethodGHeight1 {
            get {
                return ResourceManager.GetString("RuntimeErrMesMethodGHeight1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}関数:GraphicsIDに負の値({1})が指定されました 的本地化字符串。
        /// </summary>
        public static string RuntimeErrMesMethodGraphicsID0 {
            get {
                return ResourceManager.GetString("RuntimeErrMesMethodGraphicsID0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}関数:GraphicsIDの値({1})が大きすぎます 的本地化字符串。
        /// </summary>
        public static string RuntimeErrMesMethodGraphicsID1 {
            get {
                return ResourceManager.GetString("RuntimeErrMesMethodGraphicsID1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}関数:GraphicsのWidthに0以下の値({1})が指定されました 的本地化字符串。
        /// </summary>
        public static string RuntimeErrMesMethodGWidth0 {
            get {
                return ResourceManager.GetString("RuntimeErrMesMethodGWidth0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}関数:GraphicsのWidthに{2}以上の値({1})が指定されました 的本地化字符串。
        /// </summary>
        public static string RuntimeErrMesMethodGWidth1 {
            get {
                return ResourceManager.GetString("RuntimeErrMesMethodGWidth1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}関数:第{1}引数は省略できません 的本地化字符串。
        /// </summary>
        public static string SyntaxErrMesMethodDefaultArgumentNotNullable0 {
            get {
                return ResourceManager.GetString("SyntaxErrMesMethodDefaultArgumentNotNullable0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}関数:引数の数が間違っています 的本地化字符串。
        /// </summary>
        public static string SyntaxErrMesMethodDefaultArgumentNum0 {
            get {
                return ResourceManager.GetString("SyntaxErrMesMethodDefaultArgumentNum0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}関数:少なくとも{1}個の引数が必要です 的本地化字符串。
        /// </summary>
        public static string SyntaxErrMesMethodDefaultArgumentNum1 {
            get {
                return ResourceManager.GetString("SyntaxErrMesMethodDefaultArgumentNum1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}関数:引数の数が多すぎます 的本地化字符串。
        /// </summary>
        public static string SyntaxErrMesMethodDefaultArgumentNum2 {
            get {
                return ResourceManager.GetString("SyntaxErrMesMethodDefaultArgumentNum2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}関数:第{1}引数の型が間違っています 的本地化字符串。
        /// </summary>
        public static string SyntaxErrMesMethodDefaultArgumentType0 {
            get {
                return ResourceManager.GetString("SyntaxErrMesMethodDefaultArgumentType0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}関数:ColorMatrixに5x5以上の二次元数値型配列変数でない引数が指定されました 的本地化字符串。
        /// </summary>
        public static string SyntaxErrMesMethodGraphicsColorMatrix0 {
            get {
                return ResourceManager.GetString("SyntaxErrMesMethodGraphicsColorMatrix0", resourceCulture);
            }
        }
    }
}
